import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./components/ThemeProvider";
import Nested from "./Nested";

const inter = Roboto({ subsets: ["latin-ext"], weight: [ "100", "300", "400", "500", "700", "900" ] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nested>{children}</Nested>
      </body>
    </html>
  );
}
